sudo: required
dist: trusty
language: python

python: "3.5"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y emacs24-nox libxml2-dev libxslt1-dev texlive org-mode pandoc pandoc-citeproc

install:
  - pip install --upgrade setuptools
  - pip install Nikola[extras]
  - nikola plugin -i orgmode

script: nikola build

after_success:
  - chmod 755 ./.push_gh_pages.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.push_gh_pages.sh
